import http from 'node:http';import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {DatabaseSync} from 'node:sqlite';import {fileURLToPath} from 'node:url';
const ROOT=path.dirname(fileURLToPath(import.meta.url));const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.png':'image/png','.jpg':'image/jpeg','.jpeg':'image/jpeg','.webp':'image/webp','.svg':'image/svg+xml'};
export function createShop({dataDir=process.env.DATA_DIR||path.join(ROOT,'data'),origin=process.env.PUBLIC_URL||'http://localhost:3000',password=process.env.ADMIN_PASSWORD,email=process.env.ADMIN_EMAIL||'shopicutenic@gmail.com',production=process.env.NODE_ENV==='production'}={}){
 if(!password||password.length<12)throw Error('Set ADMIN_PASSWORD to a private password of at least 12 characters');origin=new URL(origin).origin;if(production&&!origin.startsWith('https://'))throw Error('PUBLIC_URL must use HTTPS in production');fs.mkdirSync(path.join(dataDir,'uploads'),{recursive:true});const db=new DatabaseSync(path.join(dataDir,'shop.sqlite'));db.exec('PRAGMA journal_mode=WAL; CREATE TABLE IF NOT EXISTS metadata (key TEXT PRIMARY KEY, value TEXT NOT NULL); CREATE TABLE IF NOT EXISTS products (id TEXT PRIMARY KEY, data TEXT NOT NULL); CREATE TABLE IF NOT EXISTS sessions (token TEXT PRIMARY KEY, expires INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS login_attempts (address TEXT PRIMARY KEY, count INTEGER NOT NULL, expires INTEGER NOT NULL);');const salt=crypto.randomBytes(16);const passHash=crypto.scryptSync(password,salt,64);const hash=x=>crypto.createHash('sha256').update(x).digest('hex');if(!db.prepare("SELECT value FROM metadata WHERE key='seeded'").get()){for(const p of JSON.parse(fs.readFileSync(path.join(ROOT,'seed.json')))){db.prepare('INSERT INTO products VALUES (?,?)').run(p.id,JSON.stringify(p))}db.prepare('INSERT INTO metadata VALUES (?,?)').run('seeded','true')}
 const json=(res,status,data)=>{res.writeHead(status,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(data))};
 const session=req=>{const m=(req.headers.cookie||'').match(/(?:^|;\s*)icutenic_session=([a-f0-9]{64})/);return m&&db.prepare('SELECT expires FROM sessions WHERE token=? AND expires>?').get(hash(m[1]),Date.now())};
 const body=async req=>{let size=0;const chunks=[];for await(const chunk of req){size+=chunk.length;if(size>8*1024*1024)throw Object.assign(Error('Upload must be under 8 MB'),{status:413});chunks.push(chunk)}return Buffer.concat(chunks)};
 const server=http.createServer(async(req,res)=>{res.setHeader('x-content-type-options','nosniff');res.setHeader('referrer-policy','same-origin');res.setHeader('content-security-policy',"default-src 'self'; img-src 'self' blob:; style-src 'self' 'unsafe-inline'; script-src 'self'; frame-ancestors 'none'; form-action 'self'; base-uri 'self'");try{const url=new URL(req.url,origin);const route=url.pathname;const authenticated=!!session(req);if(req.method!=='GET'&&req.method!=='HEAD'&&req.headers.origin!==origin)return json(res,403,{error:'Refresh the page and try again'});
 if(route==='/api/login'&&req.method==='POST'){const address=req.socket.remoteAddress||'unknown';const a=db.prepare('SELECT * FROM login_attempts WHERE address=?').get(address);if(a&&a.expires>Date.now()&&a.count>=10)return json(res,429,{error:'Too many attempts Please wait 15 minutes'});const d=JSON.parse((await body(req)).toString());const valid=typeof d.password==='string'&&d.password.length<1024&&crypto.timingSafeEqual(crypto.scryptSync(d.password,salt,64),passHash)&&d.email===email;if(!valid){db.prepare('INSERT OR REPLACE INTO login_attempts VALUES (?,?,?)').run(address,a&&a.expires>Date.now()?a.count+1:1,Date.now()+900000);return json(res,401,{error:'Email or password is incorrect'})}db.prepare('DELETE FROM login_attempts WHERE address=?').run(address);db.prepare('DELETE FROM sessions WHERE expires<?').run(Date.now());const token=crypto.randomBytes(32).toString('hex');db.prepare('INSERT INTO sessions VALUES (?,?)').run(hash(token),Date.now()+8*3600000);res.setHeader('set-cookie',`icutenic_session=${token}; HttpOnly; SameSite=Strict; Path=/; Max-Age=28800${production?'; Secure':''}`);return json(res,200,{ok:true})}
 if(route==='/api/logout'&&req.method==='POST'){const m=(req.headers.cookie||'').match(/icutenic_session=([a-f0-9]{64})/);if(m)db.prepare('DELETE FROM sessions WHERE token=?').run(hash(m[1]));res.setHeader('set-cookie','icutenic_session=; HttpOnly; SameSite=Strict; Path=/; Max-Age=0');return json(res,200,{ok:true})}
 if(route==='/api/owner')return json(res,200,{owner:authenticated});
 if(route==='/api/products'&&req.method==='GET')return json(res,200,db.prepare('SELECT data FROM products').all().map(x=>JSON.parse(x.data)));
 if(route==='/api/export'&&req.method==='GET'){if(!authenticated)return json(res,401,{error:'Sign in first'});res.setHeader('content-disposition','attachment; filename="icutenic-products.json"');return json(res,200,db.prepare('SELECT data FROM products').all().map(x=>JSON.parse(x.data)))}
 if(route.startsWith('/api/products')&&req.method!=='GET'){if(!authenticated)return json(res,401,{error:'Sign in first'});const id=route.split('/')[3];if(req.method==='DELETE'&&id){db.prepare('DELETE FROM products WHERE id=?').run(id);return json(res,200,{ok:true})}if(!['POST','PUT'].includes(req.method))return json(res,405,{error:'Method not allowed'});const bytes=await body(req);const f=await new Request(origin+route,{method:'POST',headers:{'content-type':req.headers['content-type']||''},body:bytes}).formData();const existing=id?db.prepare('SELECT data FROM products WHERE id=?').get(id):null;if(id&&!existing)return json(res,404,{error:'Product not found'});const old=existing?JSON.parse(existing.data):null;const name=String(f.get('name')||'').trim();const rawPrice=String(f.get('price')||'');const price=rawPrice?Number(rawPrice):null;const category=String(f.get('category'));const sizes=f.getAll('sizes').map(String);const description=String(f.get('description')||'');if(!name||name.length>100||(price!==null&&(!Number.isFinite(price)||price<=0||price>10000))||!['SHIRTS','PANTS','HOODIES','ACCESSORIES'].includes(category)||sizes.some(x=>!['S','M','L'].includes(x))||(category!=='ACCESSORIES'&&!sizes.length)||description.length>2000)return json(res,400,{error:'Check name price category and sizes'});const variants=old?.variants?[...old.variants]:[];const photos=f.getAll('photos').filter(x=>x instanceof File&&x.size);const colors=String(f.get('colors')||'').split(',').map(x=>x.trim()).filter(Boolean);if(photos.length>10||photos.length&&colors.length!==photos.length||colors.some(x=>x.length>40))return json(res,400,{error:'Enter one color name per uploaded photo in the same order'});const validated=[];for(let i=0;i<photos.length;i++){const photo=photos[i];if(photo.size>5*1024*1024||!['image/png','image/jpeg','image/webp'].includes(photo.type))return json(res,400,{error:'Use PNG JPG or WebP photos under 5 MB'});const data=Buffer.from(await photo.arrayBuffer());const valid=photo.type==='image/png'?data.subarray(0,8).equals(Buffer.from([137,80,78,71,13,10,26,10])):photo.type==='image/jpeg'?data[0]===255&&data[1]===216:data.subarray(0,4).toString()==='RIFF'&&data.subarray(8,12).toString()==='WEBP';if(!valid)return json(res,400,{error:'Invalid image file'});validated.push({data,ext:photo.type==='image/png'?'.png':photo.type==='image/jpeg'?'.jpg':'.webp',color:colors[i]})}if(validated.length)variants.length=0;if(!old&&!validated.length)return json(res,400,{error:'Upload at least one photo'});for(const v of validated){const filename=crypto.randomUUID()+v.ext;fs.writeFileSync(path.join(dataDir,'uploads',filename),v.data);variants.push({color:v.color,image:'/uploads/'+filename})}const p={id:old?.id||crypto.randomUUID(),name,price,category,sizes,description,variants,status:'coming-soon'};db.prepare('INSERT OR REPLACE INTO products VALUES (?,?)').run(p.id,JSON.stringify(p));return json(res,old?200:201,{ok:true,product:p})}
 if(route==='/admin'&&!authenticated){res.writeHead(302,{location:'/login'});return res.end()}
 if(route==='/health')return json(res,200,{ok:true});if(route==='/robots.txt'){res.writeHead(200,{'content-type':'text/plain'});return res.end('User-agent: *\nDisallow: /admin\nDisallow: /login\nDisallow: /api/\n')}
 const requested=route==='/'?'index.html':route==='/admin'?'admin.html':route==='/login'?'login.html':decodeURIComponent(route).slice(1);const base=route.startsWith('/uploads/')?path.join(dataDir,'uploads'):path.join(ROOT,'public');const target=path.resolve(base,route.startsWith('/uploads/')?requested.slice(8):requested);if(!target.startsWith(base+path.sep)||!fs.existsSync(target)||!fs.statSync(target).isFile()){res.writeHead(404);return res.end('Page not found')}res.setHeader('content-type',mime[path.extname(target)]||'application/octet-stream');res.setHeader('cache-control',route==='/admin'||route==='/login'?'no-store':'public,max-age=300');res.end(fs.readFileSync(target));
 }catch(e){console.error(e.message);json(res,e.status||500,{error:e.status?e.message:'Could not complete this action Please try again'})}});return {server,db};
}
if(process.argv[1]===fileURLToPath(import.meta.url)){const {server}=createShop();server.listen(Number(process.env.PORT||3000),'0.0.0.0',()=>console.log('ICUTENIC is ready'))}
